import Head from 'next/head';
import React from 'react';
import styles from '@/styles/Home.module.scss';
import { BasicTemplate } from '@/components/templates/BasicTemplate';
import { About } from '@/components/organisms/About';
import { WebsiteDescription } from '@/components/organisms/WebsiteDescription';
import { SampleCode } from '@/components/organisms/SampleCode';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BasicTemplate>
        <div className={styles.pageWrapper}>
          <About />
          <WebsiteDescription />
          <SampleCode />
        </div>
      </BasicTemplate>
    </>
  );
}
