@startuml Domain Model
skinparam style strictuml
skinparam DefaultFontName Arial
skinparam DefaultFontSize 16
skinparam DefaultFontStyle bold
skinparam ArrowThickness 2.2
skinparam ArrowColor #gray
hide empty members

header Page Header

title 合流に関する仕様（同一チーム内に合流可能なチームが無い）


left to right direction
  usecase "退会" as Withdrawal

  actor "管理者" as admin


rectangle プラハチャレンジシステム as PCS {
    rectangle チーム as team {
      rectangle ペア1 as pair1 {
        :A: as A
        :B: as B
      }
      rectangle ペア2 as pair2 {
        :C: as C
        :D: as D
      }
    }
}

rectangle 外部サービス  {
    rectangle メールサービス as mailService {
    }
}

card mail [
  合流難民通知メール
  ----
  退会者名
  ....
  残された参加者の名前
]

Note right of D
  同一チーム内に合流可能なチームが存在しない
end note

A --> Withdrawal
B --> Withdrawal
C --> Withdrawal

PCS --> mailService
mailService --> mail
mail --> admin



@enduml