@startuml Domain Model
skinparam style strictuml
skinparam DefaultFontName Arial
skinparam DefaultFontSize 16
skinparam DefaultFontStyle bold
skinparam ArrowThickness 2.2
skinparam ArrowColor #gray
hide empty members

header Page Header

title 合流に関する仕様（ペアの人数が均等ではないケース）


left to right direction
  usecase "退会" as Withdrawal

rectangle プラハチャレンジシステム as PCS {
    rectangle チーム as team {
      rectangle ペア1 as pair1 {
        :A: as A
        :B: as B
      }
      rectangle ペア2 as pair2 {
        :C: as C
        :D: as D
      }
      rectangle ペア3 as pair3 {
        :E: as F
        :G: as G
        :H: as H
      }
    }
}

Note left of D
  ペアの人数が一人になった場合、
  同一チームのペアのうち
  最も人数が少ないペアに移動
end note

C --> Withdrawal
D ..> pair1



@enduml