name: Jest

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'architecture/PrahaChallenge/backend/**'

defaults:
  run:
    working-directory: ./architecture/PrahaChallenge/backend

jobs:
  jest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test
