export const INJECTION_TOKENS = {
  PARTICIPANT_REPOSITORY: Symbol('PARTICIPANT_REPOSITORY'),
  PAIR_REPOSITORY: Symbol('PAIR_REPOSITORY'),
  TEAM_REPOSITORY: Symbol('TEAM_REPOSITORY'),
  PARTICIPANT_ASSIGNMENT_REPOSITORY: Symbol(
    'PARTICIPANT_ASSIGNMENT_REPOSITORY',
  ),
} as const;
